library('bsplus')
library('DT')
library('htmltools')
library('MALDIquant')
library('plyr')
library('pracma')
library('shiny')
library('shinyjs')
shiny::addResourcePath(prefix = 'pics', directoryPath = 'inst/www')