default:
  app_name: IsoCor
  app_version: !expr as.character(utils::packageVersion("IsoCor"))
  app_date: !expr as.character(utils::packageDate("IsoCor"))
  app_wd: !expr system.file(package = "IsoCor")
  app_prod: no
  bam_server: no
production:
  app_prod: yes
dev:
  app_wd: !expr here::here()
